---
title: "info"
author: "Arnfinn Hykkerud Steindal"
date: "21. september 2018"
output: html_document
runtime: shiny
---

<br>

Dataene som presenteres er fra Norsk pasientregister (NPR), og inneholder alle kontakter med somatisk spesialisttjeneste ved sykehusene i Helse Nord RHF, samt alle kontakter for bosatte i Helse Nord RHF sitt opptaksområde.

- Bakgrunnstallene er hentet fra avdelingsoppholdsfiler fra NPR og er aggregert på ulike nivå.
  - **Sykehusopphold**: Avdelingsopphold som er kodet som døgnopphold eller dagbehandlings *ved samme sykehus* som har foregått nært i tid eller samtidig regnes som ett opphold. Nært i tid er mindre enn åtte timer mellom utskrivelse fra ett opphold til innskrivelse til et nytt opphold. Antall DRG-poeng hentes fra det bærende oppholdet, som er det oppholdet med høyest DRG-poeng. Alle polikliniske konsultasjoner regnes som kontakter, uavhengig av nærhet i tid til andre kontakter.
  - **Justert for overføringer**: Ved justering for overføringer er alle døgn- og dagopphold med mindre enn åtte timer mellom utskrivelse fra ett opphold til innskrivelse til neste opphold regnet som ett opphold, *uavhengig av hvor pasienten er behandlet*. Liggetiden regnes som tiden fra innskrivelse ved første opphold til utskrivelse fra siste opphold. Behandlingssted og antall DRG-poeng hentes fra det bærende oppholdet, som er det oppholdet med høyest DRG-poeng. Alle polikliniske konsultasjoner regnes som kontakter, uavhengig av nærhet i tid til andre kontakter.
- Ratene er beregnet ut i fra befolkningstall fra SSB for hvert opptaktsområde på RHF, HF eller sykehus-nivå, og er justert for kjønns- og alderssammensetningen i opptaktsområdene. Referansepopulasjonen er populasjon i Helse Nord RHF sitt opptaktsområde i 2016.
- Det er lagt opp til høy fleksibilitet, som i enkelte tilfeller kan gi ikke-intuitive resultater. Tabellverket burde derfor brukes med omhu.
- Hvis antall kontaker eller antall liggedøgn er mindre enn 5 i en celle er tallet erstattet med strek, av hensyn til personvernet.
- Tabell som lages kan lagres som en csv-fil, som så kan åpnes i Excel for videre analyse.
- Fraskrivelse: Publikasjonen har benyttet data fra NPR. Brukerne er eneansvarlig for tolkning og presentasjon av de utleverte data. NPR har ikke ansvar for analyser eller tolkninger basert på de utleverte data.
- Hvis man opplever feil eller problemer kan man rapportere dette som en *issue* <a href="https://github.com/mong/tmongr/issues" target="_blank">her</a> . Eventuelt kan man sende en mail til arnfinn.steindal@skde.no

Versjon: <a href="https://github.com/mong/tmongr/releases/tag/v3.1.0" target="_blank">3.1.0</a>

Tidligere versjoner:
- <a href="https://skde.shinyapps.io/tabellverk_2019_12_16/" target="_blank">16.12.2019</a>
- <a href="https://skde.shinyapps.io/tabellverk_2019_11_22/" target="_blank">22.11.2019</a>
- <a href="https://skde.shinyapps.io/tabellverk_2019_09_12/" target="_blank">12.09.2019</a>
- <a href="https://skde.shinyapps.io/tabellverk_2019_06_03/" target="_blank">03.06.2019</a>
- <a href="https://skde.shinyapps.io/tabellverk_2018_09_21/" target="_blank">21.09.2018</a>

</br>
