#!/bin/bash

if [ ! "$TRAVIS_TAG" == "" ]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker push hnskde/tmongr
elif [[ "$TRAVIS_BRANCH" == "master" ]]; then
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker tag hnskde/tmongr hnskde/tmongr:test
  docker push hnskde/tmongr:test
else
  echo "Do not deploy. This is neither the master branch nor a release."
fi
