---
author: "Arnfinn Hykkerud Steindal"
title: "Package development"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pkgdown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# How to contribute

Development of the code is done through so called *Pull Requests* (PR) on [github](https://github.com/SKDE-Analyse/dynamiskTabellverk).

# How to make a new release

Go through the points below before tagging a new release

1. Update date and version number in `DESCRIPTION` file. Use [Semantic Versioning](https://semver.org/) with `MAJOR.MINOR.PATCH`:
    - `MAJOR + 1` when breaking the API 
    - `MINOR + 1` when adding features
    - `PATCH + 1` when fixing bugs or polish code
2. Update "version number" in `inst/application/Rmd/info.Rmd` file. This will be the date of the latest major update of the official web page, and an incrementing last letter.
3. Update the changelog (update `NEWS.md`)
4. *Roxygenise* the package
```
roxygen2::roxygenise()
```
5. Build the documentation (to see if it looks ok). This is also done by [Travis CI](https://travis-ci.org/SKDE-Analyse/dynamiskTabellverk/builds) after pushing to the master branch on [github](https://github.com/SKDE-Analyse/dynamiskTabellverk).
```
pkgdown::build_site()
```
6. Test the package
```
devtools::test()
```
7. Make a new branch, commit everything, push to github
```
git co -b feature-2
git add .
git commit
git push -u origin feature-2
```
8. Open a PR and wait for it to be squashed into master
9. Draft a new release on [github](https://github.com/SKDE-Analyse/dynamiskTabellverk/releases/new)


<!--
## How to install pkgdown

```
httr::set_config(httr::use_proxy(url="<proxy>", port=<port>)) # Only if behind HN proxy
devtools::install_github("r-lib/pkgdown")
```
-->


