app <- ShinyDriver$new("../", seed = 100)
app$snapshotInit("app-test1")
Sys.sleep(1)
app$setInputs(xcol1 = "boomr_sykehus")
Sys.sleep(1)
app$snapshot()
app$setInputs(keepNames = TRUE)
Sys.sleep(1)
app$setInputs(prosent = TRUE)
Sys.sleep(1)
app$snapshot()
