# nolint start
app <- shinytest::ShinyDriver$new("../", seed = 100)
app$snapshotInit("app-test2")
Sys.sleep(0.2)
app$snapshot()
app$setInputs(valg_datasett = "data2")
Sys.sleep(1.0)
app$snapshot()
#app$setInputs(alder = c("18 - 49 år", "50 - 74 år", "75 år og over"))
#app$setInputs(hastegrad2 = c("Akutt medisin", "Planlagt kirurgi", "Akutt kirurgi", "Ukjent"))
#app$setInputs(hastegrad1 = c("Planlagt", "Ukjent"))
#app$setInputs(behandlingsniva = c("Dagbehandling", "Poliklinikk", "Avtalespesialist"))
#Sys.sleep(1)
#app$snapshot()
#app$setInputs(xcol1 = "kjonn")
#Sys.sleep(1)
#app$snapshot()
# nolint end
