test_that("app_ui", {
  ref_chr <- as.character(purrr::flatten(app_ui()))[4]
  expect_true(grepl("www/hn.png", ref_chr, fixed = TRUE))
  expect_true(grepl("color: #003A8C", ref_chr, fixed = TRUE))
  expect_true(grepl("color: #808080", ref_chr, fixed = TRUE))
  expect_true(grepl("max-width: 1200px", ref_chr, fixed = TRUE))
  expect_true(grepl("Pasientstrømmer, Helse Nord RHF", ref_chr, fixed = TRUE))
  expect_true(grepl("just_overf", ref_chr, fixed = TRUE))
  expect_true(grepl("behandlingsniva", ref_chr, fixed = TRUE))
  expect_true(grepl("hastegrad1", ref_chr, fixed = TRUE))
  expect_true(grepl("keep_names", ref_chr, fixed = TRUE))
  expect_true(grepl("Alle kontakter", ref_chr, fixed = TRUE))
  expect_true(grepl("Poliklinikk", ref_chr, fixed = TRUE))
  expect_true(grepl("alder", ref_chr, fixed = TRUE))
  expect_true(grepl("hastegrad2", ref_chr, fixed = TRUE))
  expect_true(grepl("aar", ref_chr, fixed = TRUE))
  expect_true(grepl("shiny-html-output", ref_chr, fixed = TRUE))
  expect_true(grepl("Informasjon", ref_chr, fixed = TRUE))
  expect_true(grepl("Dataene som presenteres er fra Norsk pasientregister", ref_chr, fixed = TRUE))
  expect_true(grepl("Ratene er beregnet ut i fra befolkningstall fra SSB", ref_chr, fixed = TRUE))
})

test_that("server_ui", {
  shiny::testModule(app_server, {
    expect_equal(class(meny), "reactivevalues")
    expect_equal(class(output), "shinyoutput")
    expect_equal(as.character(output$instilling[["html"]]), "<h4>Andre instillinger</h4>")
    session$setInputs(rad2 = "ingen")

    expect_null(output$alle)
    expect_equal(as.character(output$instilling[["html"]]), "<h4>Andre instillinger</h4>")
    session$setInputs(overf = FALSE)
    session$setInputs(overf = TRUE)

    expect_equal_to_reference(output$figurtekst, "data/empty_figurtekst.rds")

    expect_true(grepl("Last ned data", as.character(output$lastned[["html"]])))
    expect_true(grepl("downloadData", as.character(output$lastned[["html"]]), ))
    session$setInputs(tab = "dogn")
    expect_null(output$alle)

    expect_null(lageParametere())
    session$setInputs(xcol1 = "boomr_rhf")
    expect_null(lageParametere())
    session$setInputs(snitt = FALSE)
    session$setInputs(keep_names = FALSE)

    session$setInputs(xcol2 = "behandlende_rhf")
    expect_equal_to_reference(lageParametere(), "data/lageParametere.rds")

    session$setInputs(xcol2 = "ingen")
    expect_equal_to_reference(lageParametere(), "data/lageParametere2.rds")
    session$setInputs(xcol2 = "behandlende_rhf")
    session$setInputs(prosent = FALSE)
    expect_equal_to_reference(lageParametere(), "data/lageParametere.rds")
    session$setInputs(prosent = TRUE)
    expect_equal_to_reference(lageParametere(), "data/lageParametere3.rds")
    expect_equal_to_reference(makeTable(), "data/makeTable.rds")
    session$setInputs(prosent = FALSE)
    expect_equal_to_reference(makeTable(), "data/makeTable2.rds")
    session$setInputs(xcol2 = "boomr_rhf")
    expect_equal_to_reference(makeTable(), "data/makeTable3.rds")
  })
})

test_that("run_app", {
  expect_equal(class(run_app()), "shiny.appobj")
  expect_equal(class(run_app()$httpHandler), "function")
  expect_equal(class(run_app()$options), "list")
  expect_equal(class(run_app()$serverFuncSource), "function")
})
